image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test

black:
  stage: Static Analysis
  script:
  - black --check .

mypy:
  stage: Static Analysis
  script:
  - mypy -p gitdraw

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - pylint tests
  - pylint gitdraw

pytest:
  stage: Test
  script:
  - pytest --cov=gitdraw --cov-report term-missing